# Generated by Django 4.1.3 on 2022-11-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_category_name_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
